# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
 desc "Deploy to Firebase app distribution"
 lane :deploy do
  begin
  firebase_app_distribution(
   groups: "testers",
   release_notes: "Fixing bug in features",
   apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
   firebase_cli_path: "/usr/local/bin/firebase",
   firebase_cli_token: "1//0gbTIcHcjdNl2CgYIARAAGBASNwF-L9IrG1059SuFseaDSCzv4DywDaWo8H-FVExbAHWjjdSkIMn54dcUedf6JMPr6KHP9I8b9tE",
   app: "1:883142288503:android:8be783e4c7e7576bc41272"
  )
  end
 end
end